name = "ElectronicStructure"
uuid = "f7ec468b-4310-4c77-90aa-f73697106762"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.1.8"

[deps]
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
ZChop = "8603256b-76ad-53fe-b511-38a38e6437cd"

[compat]
ZChop = ">= 0.3.10"
julia = ">= 1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
